name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Fizzbuzz
      id: fizzbuzz
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Fizzbuzz
        setup-command: "./setup.sh"
        command: "./tests/run.sh"
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        FIZZBUZZ_RESULTS: "${{steps.fizzbuzz.outputs.result}}"
      with:
        runners: fizzbuzz
